import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../theme';
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.surface },
  header: { backgroundColor: colors.surfaceSecondary, borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: spacing.lg, paddingBottom: spacing.md, gap: spacing.md },
  title: { fontSize: 24, fontWeight: '700', color: colors.onSurface },
  row: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, alignItems: 'center' },
  mode: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.surfaceTertiary },
  active: { backgroundColor: colors.brandPrimary, borderColor: colors.brandPrimary },
  text: { color: colors.onSurface, fontSize: 14, fontWeight: '600' },
  onBrand: { color: colors.onBrand },
  map: { height: 320, marginBottom: spacing.md },
  section: { paddingHorizontal: spacing.lg, gap: spacing.md, marginBottom: spacing.xl },
  hint: { color: colors.muted, fontSize: 13, lineHeight: 19 },
  small: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, minHeight: 44, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceTertiary },
  primary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, minHeight: 48, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.brandPrimary },
  disabled: { opacity: .45 },
  label: { fontSize: 13, fontWeight: '700', color: colors.onSurface, marginTop: spacing.sm, textTransform: 'uppercase', letterSpacing: .5 },
  chip: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: spacing.md, borderRadius: radius.pill, backgroundColor: colors.surfaceTertiary, borderWidth: 1, borderColor: colors.border },
  dot: { width: 10, height: 10, borderRadius: 5 },
  input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: spacing.md, paddingVertical: 12, fontSize: 15, color: colors.onSurface, backgroundColor: colors.surfaceSecondary },
  error: { color: colors.error, fontSize: 14, lineHeight: 20 },
  notice: { color: colors.brandPrimary, fontSize: 14, lineHeight: 20, fontWeight: '600' },
  card: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surfaceSecondary, padding: spacing.md, gap: spacing.sm },
  stats: { flexDirection: 'row', gap: spacing.sm },
  stat: { flex: 1, backgroundColor: colors.surfaceTertiary, borderRadius: radius.md, padding: spacing.md, gap: 4 },
  number: { color: colors.onSurface, fontSize: 17, fontWeight: '700' },
  overlay: { flex: 1, backgroundColor: colors.surfaceInverse, justifyContent: 'center', padding: spacing.lg },
  dialog: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.xl, gap: spacing.lg, maxHeight: '90%' },
  previewHeader: { paddingHorizontal: spacing.lg, paddingBottom: spacing.md, gap: spacing.sm },
});